### ISSUE TITLE
Style Route Icon

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/eraser-map#66] opened 2015-10-30 16:00 UTC
https://github.com/tangrams/eraser-map/blob/android/eraser-map.yaml#L764-L787

Currently a route icon layer is missing all together, I am going to add one as a placeholder in the android branch, for it to be used in eraser-map app code.

**Comment by nvkelso** [comment] 2015-10-30 16:02
Please add it in the main branch, too, so there are less merge conflicts later. (Web map will need this.)

**Comment by tallytalwar** [comment] 2015-10-30 16:02
Cool, will do and rebase android branch. Thanks

**Comment by nvkelso** [comment] 2015-10-30 20:40
This is a duplicate of: https://github.com/tangrams/eraser-map/issues/64.

**Closed as completed by nvkelso** 2015-10-30 20:40 UTC
